#!/usr/bin/env ruby
# generated by org-babel-tangle
# [[file:~/Documentos/anem/anem16/assembler/assembler.org::*Limpeza][limpa]]
entrada = IO.new(0,'r')
NOP = /NOP/
LIW = /LIW\s+\$(\d{1,2}),\s*(\d+)/
indice = 0
entrada.each do |linha|
  linha.sub!( /--.*$/ , '')
  linha.upcase!
  linha.gsub!(NOP,'ADD $0,$0')
  linha.gsub!(LIW){"LIU $#{$1}, #{$2.to_i/256}\n\tLIL $#{$1}, #{$2.to_i%256}"}
  linha.strip!
  puts linha unless linha.empty?
end
# limpa ends here
